# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=20)),
                ('menu', models.ImageField(null=True, upload_to='images/')),
                ('map', models.ImageField(null=True, upload_to='images/')),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('votes', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=4)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rest_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Type'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Town'),
        ),
    ]
