# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20160807_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
