# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_town_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
